name: Build and Deploy with Toucan

on:
  push:
    branches: [main]

jobs:
  call-toucan-workflow:
    uses: BinaryBirds/github-workflows/.github/workflows/toucan_deploy.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write